[package]
name = "profiling"
version = "0.0.0"
authors = ["Ilya (Marshal) <ilya@marshal.dev>"]
edition = "2021"

[dependencies]
libipld = { path = ".." }

structopt = "0.3.26"
clap = "4.5.29"

[dependencies.pyo3]
version = "0.25.1"
